version: '3.8'
services:
  todofront:
    build: ./todo-app/front-end/
    depends_on:
      - todoback
    ports:
      - 3000:3000
    restart: on-failure
    environment:
      - REACT_APP_API_HOST=todoback

  todoback:
    build: ./todo-app/back-end/
    ports:
      - 3001:3001
    restart: on-failure

  todotests:
    build: ./todo-app/tests/
    depends_on: 
      - todoback
      - todofront
    restart: on-failure
    environment:
      - FRONT_HOST=todofront
